version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:5432 -timeout 30s ./.docker/app/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=app
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    restart: always
    volumes:
      - .:/usr/src
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./.docker/postgres-data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
